### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by vickkie** [afridevelopers/support#21]
### Name

vickkie

### Additional Context

Subject: Request to Join

 My name is vickkie from Kenya, and I am reaching out to express my interest in joining the Organization on GitHub.

I have been following the work of afridevelopers Community for some time now, and I am deeply impressed by the projects and contributions that the team has made.

 I believe that my skills and experiences align well with the goals and values of afridevelopers Community, and I am excited about the possibility of contributing to your ongoing projects and joining the team.

**Comment by victorpreston** [comment]
Welcome Vickkie
We look forward to collaboration with you and your input in the community
